dist: trusty

jobs:
  include:
  - stage: build
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_USERNAME/c4-ecommerce .
    - docker push $DOCKER_USERNAME/c4-ecommerce
    if: branch = master